// Code generated by "stringer -type=Category"; DO NOT EDIT.

package object

import "strconv"

const _Category_name = "NoneWeaponWandStaffTreasureArmorFoodOtherCorpse"

var _Category_index = [...]uint8{0, 4, 10, 14, 19, 27, 32, 36, 41, 47}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
