// Code generated by "stringer -type=Slot"; DO NOT EDIT.

package equip

import "fmt"

const _Slot_name = "NONEPRIMARY_HANDSECONDARY_HAND"

var _Slot_index = [...]uint8{0, 4, 16, 30}

func (i Slot) String() string {
	if i < 0 || i >= Slot(len(_Slot_index)-1) {
		return fmt.Sprintf("Slot(%d)", i)
	}
	return _Slot_name[_Slot_index[i]:_Slot_index[i+1]]
}
